/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "TQUIC",
  "tagline": "High performance, light weight and cross platform QUIC library",
  "favicon": "img/favicon.ico",
  "url": "https://your-docusaurus-test-site.com",
  "baseUrl": "/zh/",
  "organizationName": "tencent",
  "projectName": "tquic",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "zh"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/data/home/jeffyang/workroot/github/tquic/website/sidebars.js",
          "editUrl": "https://github.com/tencent/tquic-website/tree/main/packages/create-docusaurus/templates/shared/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/tencent/tquic-website/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": "/data/home/jeffyang/workroot/github/tquic/website/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "TQUIC",
      "logo": {
        "alt": "TQUIC Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "文档"
        },
        {
          "to": "/blog",
          "label": "博客",
          "position": "left"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "href": "https://github.com/tencent/tquic",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "文档",
          "items": [
            {
              "label": "快速开始",
              "to": "docs/category/getting-started"
            },
            {
              "label": "常见问题",
              "to": "docs/category/frequently-asked-questions"
            }
          ]
        },
        {
          "title": "项目",
          "items": [
            {
              "label": "用户案例",
              "href": "https://github.com/tencent/tquic/blob/develop/ADOPTERS.md"
            },
            {
              "label": "路线图",
              "href": "https://github.com/tencent/tquic/milestones"
            },
            {
              "label": "需求反馈",
              "href": "https://github.com/tencent/tquic/issues"
            },
            {
              "label": "版本记录",
              "href": "https://github.com/tencent/tquic/releases"
            },
            {
              "label": "参与贡献",
              "to": "/docs/category/contributing"
            }
          ]
        },
        {
          "title": "社区",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/tencent/tquic"
            },
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/tquic"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/tquic"
            }
          ]
        },
        {
          "title": "资讯",
          "items": [
            {
              "label": "博客",
              "to": "/blog"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/tquic"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 TQUIC作者 | 文档发布基于CC-BY-4.0授权许可"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    [
      "/data/home/jeffyang/workroot/github/tquic/website/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js",
      {
        "indexDocs": true,
        "indexDocSidebarParentCategories": 0,
        "indexBlog": true,
        "indexPages": false,
        "language": [
          "en"
        ],
        "maxSearchResults": 8,
        "lunr": {
          "tokenizerSeparator": {},
          "b": 0.75,
          "k1": 1.2,
          "titleBoost": 5,
          "contentBoost": 1,
          "tagsBoost": 3,
          "parentCategoriesBoost": 2
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
